version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - ffmpeg
    - graphviz
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
