#!/usr/bin/env python
from setuptools import setup, find_packages
import os

entry_points = {}
entry_points['console_scripts'] = [
    'ctapipe-info = ctapipe.tools.info:main',
    'ctapipe-camdemo = ctapipe.tools.camdemo:main',
    'ctapipe-dump-triggers = ctapipe.tools.dump_triggers:main',
    'ctapipe-flow = ctapipe.flow.flow:main'
]

# Include all .c files, recursively, including those generated by
# Cython, since we can not do this in MANIFEST.in with a "dynamic"
# directory name.
c_files = []
for root, dirs, files in os.walk('ctapipe'):
    for filename in files:
        if filename.endswith('.c'):
            package_data['ctapipe'].append(
                os.path.join(
                    os.path.relpath(root, PACKAGENAME),
                    filename
                )
            )

# Note that requires and provides should not be included in the call to
# ``setup``, since these are now deprecated. See this link for more details:
# https://groups.google.com/forum/#!topic/astropy-dev/urYO8ckB2uM

setup(
    name='ctapipe',
    version='0.1.dev',
    description='CTA Python pipeline experimental version',
    author='ctapipe developers',
    author_email='karl.kosack@cea.fr',
    license='BSD3',
    url='https://github.com/cta-observatory/ctapipe',
    edit_on_github=False,
    github_project='cta-observatory/ctapipe',
    packages=find_packages(),
    tests_require=['pytest>=3.0.0'],
    setup_requires=['pytest-runner>=2.9'],
    install_requires=[
        'astropy',
        'scipy',
        'matplotlib',
        'scikit-learn',
        'numpy',
        'traitlets',
    ],
    classifiers=[
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: C',
        'Programming Language :: Cython',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Scientific/Engineering :: Astronomy',
        'Development Status :: 3 - Alpha',
    ],
    zip_safe=False,
    entry_points=entry_points,
)
