StatisticsCalculatorTool:
  allowed_tels: [1,2,3,4]
  dl1a_column_name: "image"
  output_column_name: "statistics"

PixelStatisticsCalculator:
  stats_aggregator_type: [["type", "*", "SigmaClippingAggregator"]]
  chunk_shift: 1000
  faulty_pixels_fraction: 0.1
  outlier_detector_list: [
        {
            "apply_to": "median",
            "name": "MedianOutlierDetector",
            "config": {
                "median_range_factors": [-15, 15],
            },
        },
        {
            "apply_to": "median",
            "name": "RangeOutlierDetector",
            "config": {
                "validity_range": [-20, 120],
            }
        },
        {
            "apply_to": "std",
            "name": "StdOutlierDetector",
            "config": {
                "std_range_factors": [-15, 15],
            },
        }
    ]

SigmaClippingAggregator:
  chunk_size: 2500
  max_sigma: 4
  iterations: 5
