TrainDirectionUncertaintyRegressor:
  DirectionUncertaintyRegressor:
    model_cls: 'MLPRegressor'
    model_config:
      hidden_layer_sizes: [36, 6]
      activation: 'tanh'
      solver: 'adam'
      max_iter: 20000
      tol: 1.0e-5
      random_state: 0
    features:
      - "n_telescopes_triggered"
      - "n_LSTs_triggered"
      - "n_MSTs_triggered"
      - "hillas_length_mean"
      - "hillas_length_std"
      - "hillas_width_mean"
      - "hillas_width_std"
      - "hillas_skewness_mean"
      - "hillas_skewness_std"
      - "hillas_kurtosis_mean"
      - "hillas_kurtosis_std"
      # ADD MORE FEATURES HERE

    FeatureGenerator: # On-the-fly generation of additional features
      features:
        - [ "n_telescopes_triggered", "subarray.multiplicity(tels_with_trigger)" ]
        - [ "n_LSTs_triggered", "subarray.multiplicity(tels_with_trigger, 'LST_LST_LSTCam')" ]
        - [ "n_MSTs_triggered", "subarray.multiplicity(tels_with_trigger, 'MST_MST_NectarCam')" ]