# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: R1_NectarCam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import CoreMessages_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='R1_NectarCam.proto',
  package='DataModel',
  serialized_pb=_b('\n\x12R1_NectarCam.proto\x12\tDataModel\x1a\x12\x43oreMessages.proto\"\xb2\x01\n\x0fNectarCamConfig\x12\x14\n\x0cidaq_version\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x64hs_version\x18\x02 \x01(\t\x12\x18\n\x10\x61\x63quisition_mode\x18\x03 \x01(\x07\x12\x13\n\x0bnum_modules\x18\x04 \x01(\x07\x12\x30\n\x13\x65xpected_modules_id\x18\x05 \x01(\x0b\x32\x13.DataModel.AnyArray\x12\x12\n\nalgorithms\x18\x06 \x01(\x07\"\xf7\x01\n\x0eNectarCamEvent\x12*\n\rmodule_status\x18\x01 \x01(\x0b\x32\x13.DataModel.AnyArray\x12\x1b\n\x13\x65xtdevices_presence\x18\x02 \x01(\x07\x12%\n\x08tib_data\x18\x03 \x01(\x0b\x32\x13.DataModel.AnyArray\x12&\n\tcdts_data\x18\x04 \x01(\x0b\x32\x13.DataModel.AnyArray\x12&\n\tswat_data\x18\x05 \x01(\x0b\x32\x13.DataModel.AnyArray\x12%\n\x08\x63ounters\x18\x06 \x01(\x0b\x32\x13.DataModel.AnyArray')
  ,
  dependencies=[CoreMessages_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NECTARCAMCONFIG = _descriptor.Descriptor(
  name='NectarCamConfig',
  full_name='DataModel.NectarCamConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idaq_version', full_name='DataModel.NectarCamConfig.idaq_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cdhs_version', full_name='DataModel.NectarCamConfig.cdhs_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acquisition_mode', full_name='DataModel.NectarCamConfig.acquisition_mode', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_modules', full_name='DataModel.NectarCamConfig.num_modules', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expected_modules_id', full_name='DataModel.NectarCamConfig.expected_modules_id', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='algorithms', full_name='DataModel.NectarCamConfig.algorithms', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=232,
)


_NECTARCAMEVENT = _descriptor.Descriptor(
  name='NectarCamEvent',
  full_name='DataModel.NectarCamEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_status', full_name='DataModel.NectarCamEvent.module_status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extdevices_presence', full_name='DataModel.NectarCamEvent.extdevices_presence', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tib_data', full_name='DataModel.NectarCamEvent.tib_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cdts_data', full_name='DataModel.NectarCamEvent.cdts_data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='swat_data', full_name='DataModel.NectarCamEvent.swat_data', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='counters', full_name='DataModel.NectarCamEvent.counters', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=482,
)

_NECTARCAMCONFIG.fields_by_name['expected_modules_id'].message_type = CoreMessages_pb2._ANYARRAY
_NECTARCAMEVENT.fields_by_name['module_status'].message_type = CoreMessages_pb2._ANYARRAY
_NECTARCAMEVENT.fields_by_name['tib_data'].message_type = CoreMessages_pb2._ANYARRAY
_NECTARCAMEVENT.fields_by_name['cdts_data'].message_type = CoreMessages_pb2._ANYARRAY
_NECTARCAMEVENT.fields_by_name['swat_data'].message_type = CoreMessages_pb2._ANYARRAY
_NECTARCAMEVENT.fields_by_name['counters'].message_type = CoreMessages_pb2._ANYARRAY
DESCRIPTOR.message_types_by_name['NectarCamConfig'] = _NECTARCAMCONFIG
DESCRIPTOR.message_types_by_name['NectarCamEvent'] = _NECTARCAMEVENT

NectarCamConfig = _reflection.GeneratedProtocolMessageType('NectarCamConfig', (_message.Message,), dict(
  DESCRIPTOR = _NECTARCAMCONFIG,
  __module__ = 'R1_NectarCam_pb2'
  # @@protoc_insertion_point(class_scope:DataModel.NectarCamConfig)
  ))
_sym_db.RegisterMessage(NectarCamConfig)

NectarCamEvent = _reflection.GeneratedProtocolMessageType('NectarCamEvent', (_message.Message,), dict(
  DESCRIPTOR = _NECTARCAMEVENT,
  __module__ = 'R1_NectarCam_pb2'
  # @@protoc_insertion_point(class_scope:DataModel.NectarCamEvent)
  ))
_sym_db.RegisterMessage(NectarCamEvent)


# @@protoc_insertion_point(module_scope)
