# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: R1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import CoreMessages_pb2
from . import R1_LSTCam_pb2
from . import R1_NectarCam_pb2
from . import R1_DigiCam_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='R1.proto',
  package='R1',
  serialized_pb=_b('\n\x08R1.proto\x12\x02R1\x1a\x12\x43oreMessages.proto\x1a\x0fR1_LSTCam.proto\x1a\x12R1_NectarCam.proto\x1a\x10R1_DigiCam.proto\"\xdf\x02\n\x13\x43\x61meraConfiguration\x12\x14\n\x0ctelescope_id\x18\x01 \x01(\x07\x12\x11\n\tcs_serial\x18\x02 \x01(\t\x12\x18\n\x10\x63onfiguration_id\x18\x03 \x01(\x06\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\x06\x12\x12\n\nnum_pixels\x18\x05 \x01(\r\x12\x13\n\x0bnum_samples\x18\x06 \x01(\r\x12/\n\x12\x65xpected_pixels_id\x18\x07 \x01(\x0b\x32\x13.DataModel.AnyArray\x12\x1a\n\x12\x64\x61ta_model_version\x18\x08 \x01(\t\x12-\n\tnectarcam\x18\t \x01(\x0b\x32\x1a.DataModel.NectarCamConfig\x12\'\n\x06lstcam\x18\n \x01(\x0b\x32\x17.DataModel.LstCamConfig\x12)\n\x07\x64igicam\x18\x0b \x01(\x0b\x32\x18.DataModel.DigiCamConfig\"\xf9\x02\n\x0b\x43\x61meraEvent\x12\x18\n\x10\x63onfiguration_id\x18\x01 \x01(\x06\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x06\x12\x14\n\x0ctel_event_id\x18\x03 \x01(\x06\x12\x16\n\x0etrigger_time_s\x18\x04 \x01(\x07\x12\x18\n\x10trigger_time_qns\x18\x05 \x01(\x07\x12\x14\n\x0ctrigger_type\x18\x06 \x01(\x07\x12%\n\x08waveform\x18\x07 \x01(\x0b\x32\x13.DataModel.AnyArray\x12)\n\x0cpixel_status\x18\x08 \x01(\x0b\x32\x13.DataModel.AnyArray\x12\x0e\n\x06ped_id\x18\t \x01(\x06\x12,\n\tnectarcam\x18\n \x01(\x0b\x32\x19.DataModel.NectarCamEvent\x12&\n\x06lstcam\x18\x0b \x01(\x0b\x32\x16.DataModel.LstCamEvent\x12(\n\x07\x64igicam\x18\x0c \x01(\x0b\x32\x17.DataModel.DigiCamEvent')
  ,
  dependencies=[CoreMessages_pb2.DESCRIPTOR,R1_LSTCam_pb2.DESCRIPTOR,R1_NectarCam_pb2.DESCRIPTOR,R1_DigiCam_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CAMERACONFIGURATION = _descriptor.Descriptor(
  name='CameraConfiguration',
  full_name='R1.CameraConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='telescope_id', full_name='R1.CameraConfiguration.telescope_id', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cs_serial', full_name='R1.CameraConfiguration.cs_serial', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='configuration_id', full_name='R1.CameraConfiguration.configuration_id', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='R1.CameraConfiguration.date', index=3,
      number=4, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_pixels', full_name='R1.CameraConfiguration.num_pixels', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_samples', full_name='R1.CameraConfiguration.num_samples', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expected_pixels_id', full_name='R1.CameraConfiguration.expected_pixels_id', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_model_version', full_name='R1.CameraConfiguration.data_model_version', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nectarcam', full_name='R1.CameraConfiguration.nectarcam', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lstcam', full_name='R1.CameraConfiguration.lstcam', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='digicam', full_name='R1.CameraConfiguration.digicam', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=443,
)


_CAMERAEVENT = _descriptor.Descriptor(
  name='CameraEvent',
  full_name='R1.CameraEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configuration_id', full_name='R1.CameraEvent.configuration_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='R1.CameraEvent.event_id', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tel_event_id', full_name='R1.CameraEvent.tel_event_id', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trigger_time_s', full_name='R1.CameraEvent.trigger_time_s', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trigger_time_qns', full_name='R1.CameraEvent.trigger_time_qns', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trigger_type', full_name='R1.CameraEvent.trigger_type', index=5,
      number=6, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waveform', full_name='R1.CameraEvent.waveform', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pixel_status', full_name='R1.CameraEvent.pixel_status', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ped_id', full_name='R1.CameraEvent.ped_id', index=8,
      number=9, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nectarcam', full_name='R1.CameraEvent.nectarcam', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lstcam', full_name='R1.CameraEvent.lstcam', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='digicam', full_name='R1.CameraEvent.digicam', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=823,
)

_CAMERACONFIGURATION.fields_by_name['expected_pixels_id'].message_type = CoreMessages_pb2._ANYARRAY
_CAMERACONFIGURATION.fields_by_name['nectarcam'].message_type = R1_NectarCam_pb2._NECTARCAMCONFIG
_CAMERACONFIGURATION.fields_by_name['lstcam'].message_type = R1_LSTCam_pb2._LSTCAMCONFIG
_CAMERACONFIGURATION.fields_by_name['digicam'].message_type = R1_DigiCam_pb2._DIGICAMCONFIG
_CAMERAEVENT.fields_by_name['waveform'].message_type = CoreMessages_pb2._ANYARRAY
_CAMERAEVENT.fields_by_name['pixel_status'].message_type = CoreMessages_pb2._ANYARRAY
_CAMERAEVENT.fields_by_name['nectarcam'].message_type = R1_NectarCam_pb2._NECTARCAMEVENT
_CAMERAEVENT.fields_by_name['lstcam'].message_type = R1_LSTCam_pb2._LSTCAMEVENT
_CAMERAEVENT.fields_by_name['digicam'].message_type = R1_DigiCam_pb2._DIGICAMEVENT
DESCRIPTOR.message_types_by_name['CameraConfiguration'] = _CAMERACONFIGURATION
DESCRIPTOR.message_types_by_name['CameraEvent'] = _CAMERAEVENT

CameraConfiguration = _reflection.GeneratedProtocolMessageType('CameraConfiguration', (_message.Message,), dict(
  DESCRIPTOR = _CAMERACONFIGURATION,
  __module__ = 'R1_pb2'
  # @@protoc_insertion_point(class_scope:R1.CameraConfiguration)
  ))
_sym_db.RegisterMessage(CameraConfiguration)

CameraEvent = _reflection.GeneratedProtocolMessageType('CameraEvent', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAEVENT,
  __module__ = 'R1_pb2'
  # @@protoc_insertion_point(class_scope:R1.CameraEvent)
  ))
_sym_db.RegisterMessage(CameraEvent)


# @@protoc_insertion_point(module_scope)
