# ==========================================================================
# ctapipe-process configuration file.
# version: VERSION
#
# This configuration contains a subset of options needed for a basic analysis.
# Not all possible options are shown. To get a complete list, run:
#
#     `ctapipe-process --help-all`
#
# ==========================================================================

DataWriter:
  Contact:
    # please fill in your contact information here. It will be stored in the
    # output files as provenance information
    name: YOUR-NAME-HERE
    email: YOUREMAIL@EXAMPLE.ORG
    organization: YOUR-ORGANIZATION

  # options that control what is stored in the output file by default here we
  # write nothing (can be overridden on the command-line or in subsequent config
  # files)
  overwrite: false # do not overwrite existing files
  write_images: false # store DL1 images
  write_parameters: false # store DL1 parameters
  write_stereo_shower: false # store DL2 stereo geometry
  write_raw_waveforms: false # write R0 waveforms
  write_waveforms: false # write R1 waveforms

# The CameraCalibrator takes data from R1 or DL0 to DL1a level, applying finer
# calibration and turning waveforms into images. It is run only if DL1a images
# do not already exist in the input file.
CameraCalibrator:
  # Choose an extractor type from the following possibilities:
  #'FullWaveformSum', 'FixedWindowSum', 'GlobalPeakWindowSum',
  #'LocalPeakWindowSum', 'SlidingWindowMaxSum', 'NeighborPeakWindowSum',
  #'TwoPassWindowSum', 'BaselineSubtractedNeighborPeakWindowSum'
  #
  # Note this is a telescope-wise parameter, so can be specified per telescope
  # if necessary (see below for an example)
  image_extractor_type: NeighborPeakWindowSum

# The ImageProcessor performs the DL1a-> DL1b (image parameters) transition. It
# is run only if the parameters `DataWriter.write_image_parameters=True` and the
# parameters don't already exist in the input file (or if the user forces them
# to be re-computed using DataWriter.recompute_dl1=True)
ImageProcessor:
  # The image cleaner selects pixels which have signal in them and rejects those
  # without. Options are: 'TailcutsImageCleaner', 'MARSImageCleaner',
  # 'FACTImageCleaner'
  image_cleaner_type: TailcutsImageCleaner

  # make sure you include a configuration for the image cleaner you selected
  # above here. The section named by the image_cleaner_type will be used to
  # configure it.
  TailcutsImageCleaner:
    # the thresholds for this image cleaner must be optimized for the data set
    # you are analyzing. The defaults may not be correct and should be optimized
    # for the given use case.
    #
    # These are telescope-wise parameters, where the options are patterns
    # specified in a list in order of precedence, with later options overwriting
    # earlier ones. Each pattern is a triplet of [scope, key, value], where the
    # scope can be "type" (matching to the telescope type name) or "id"
    # (matching a specific telescope ID number). In the case of "type", the key
    # should be either a telescope type string, or part of one with "*" used as
    # a wildcard match (e.g. "LST*" would match all LST telescopes). You can
    # specify a universal default value using "*" as a key. Note that specifying
    # a single value is equivalent to specifying a one-item list containing
    # [type, '*', value] .
    picture_threshold_pe: # top-level threshold in photoelectrons
      - [type, "LST*", 6.0]
      - [type, "MST*NectarCam", 8.0]
      - [type, "MST*FlashCam", 10000] # disabled for now
      - [type, "SST_ASTRI_CHEC", 4.0]
    boundary_threshold_pe: # second-level threshold in photoelectrons
      - [type, "LST*", 3.0]
      - [type, "MST*NectarCam", 4.0]
      - [type, "MST*FlashCam", 10000] # disabled for now
      - [type, "SST_ASTRI_CHEC", 2.0]
    keep_isolated_pixels: False # If False, pixels with  < min_picture_neighbors are removed.
    min_picture_neighbors: 2 # Minimum number of neighbors above threshold to consider

  # Choose which images should be parameterized:
  ImageQualityQuery:
    # quality critieria should be a list of pairs of [name,
    # filter_function_string] The filter function should take a single value
    # which is the image itself, a 1D np.array.
    quality_criteria:
      - ["enough_pixels", "lambda im: np.count_nonzero(im) > 2"]
      - ["enough_charge", "lambda im: im.sum() > 50"]

# The ShowerProcessor performs the DL1 to DL2a (reconstructed shower geometry)
# transition. It is run only if the parameter DataWriter.write_stereo_shower=True.
ShowerProcessor:
  # choose between HillasReconstructor and HillasIntersection (two
  # implementations of the standard stereo line-intersection method)
  reconstructor_type: HillasReconstructor

  HillasReconstructor:
    # Choose which telescope events should be included in the reconstruction.
    StereoQualityQuery:
      # the quality criteria here should again be a list of [name,
      # filter_function_string] pairs, with filter functions that take the set of
      # image parameters, `p` (a `ctapipe.containers.ImageParametersContainer`), as
      # an argument.
      quality_criteria:
        - [enough intensity, "lambda p: p.hillas.intensity > 50"]
        - [Positive width, "lambda p: p.hillas.width.value > 0"]
        - [enough pixels, "lambda p: p.morphology.num_pixels > 3"]
        - [not clipped, "lambda p: p.leakage.intensity_width_2 < 0.8"]
