TrainEnergyRegressor:
  n_cross_validation: 5
  Regressor:
    model_cls: ExtraTreesRegressor
    model_config:
      n_estimators: 10
      max_depth: 10
      n_jobs: -1

    features:
      - hillas_intensity
      - hillas_length
      - hillas_width
      - hillas_r
      - hillas_skewness
      - timing_slope
      - leakage_intensity_width_1
      - leakage_intensity_width_2
      - leakage_pixels_width_1
      - leakage_pixels_width_2
      - concentration_cog
      - concentration_core
      - morphology_num_pixels
      - mirror_area


TrainParticleIdClassifier:
  n_cross_validation: 5
  Classifier:
    model_cls: ExtraTreesClassifier
    model_config:
      n_estimators: 10
      max_depth: 10
      n_jobs: -1

    features:
      - hillas_intensity
      - hillas_length
      - hillas_width
      - hillas_r
      - hillas_skewness
      - timing_slope
      - leakage_intensity_width_1
      - leakage_intensity_width_2
      - leakage_pixels_width_1
      - leakage_pixels_width_2
      - concentration_cog
      - concentration_core
      - morphology_num_pixels
      - mirror_area
